#define MODULE_EXPORT

export module FULL_NAME__src_xercesc_validators_datatype_AnySimpleTypeDatatypeValidator;
#include "AnySimpleTypeDatatypeValidator.hpp"
#include "AnySimpleTypeDatatypeValidator.cpp"
