#define MODULE_EXPORT

export module FULL_NAME__src_xercesc_validators_datatype_Base64BinaryDatatypeValidator;
#include "Base64BinaryDatatypeValidator.hpp"
#include "Base64BinaryDatatypeValidator.cpp"
